server:
  port: 8080

spring:
  application:
    name: gateway

  cloud:
    gateway:
      server:
        webflux:
          globals:
            cors-configurations:
              '[/**]': # Áp dụng cho tất cả paths
                allowedOrigins: "*"  # Cho phép tất cả domain
                allowedMethods:
                  - GET
                  - POST
                  - PUT
                  - DELETE
                  - OPTIONS
                allowedHeaders: "*"  # Cho phép tất cả headers
                allowCredentials: true  # Cho phép gửi cookies/credentials
          default-filters:
            # bỏ header trùng lặp trong CORS response
            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
          routes:
            # Route 1: Identity Service
            - id: identity-service
              # lb:// = Load Balancer - Gateway sẽ tự động tìm service qua Eureka
              # identity-svc = Tên service đã đăng ký trong Eureka
              uri: lb://identity-svc
              # Predicate: Điều kiện để route này được áp dụng
              # Path=/api/identity/** = Tất cả request có path bắt đầu bằng /api/identity/
              predicates:
                - Path=/api/identity/**
              # Filters: Các bộ lọc áp dụng cho route này
              filters:
                - StripPrefix=0

            # Route 2: Event Catalog Service
            - id: event-catalog-service
              uri: lb://event-catalog-svc
              predicates:
                - Path=/api/events/**
              filters:
                - StripPrefix=0

# Redis
redis:
  host: localhost
  port: 6379
  timeout: 2000ms

# Eureka Client
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true   # Lấy danh sách service từ Eureka
    register-with-eureka: true  # Đăng ký Gateway với Eureka
  instance:
    prefer-ip-address: true  # Dùng IP thay vì hostname

# JWT
jwt:
  signerKey: ${JWT_SIGNER_KEY:secret-key-for-hmac-sha256}

  jwks-url: http://identity-svc:8081/oauth/jwks
  issuer: vticket-identity
  whitelist:
    - /auth/**
    - /oauth/**
    - /api/identity/auth/login
    - /api/identity/auth/register
    - /api/identity/token/introspect
    - /api/events
    - /api/events/**

# Logging
logging:
  level:
    com.vticket.gateway: DEBUG  # Log package gateway
    org.springframework.cloud.gateway: DEBUG  # Log Spring Cloud Gateway
    org.springframework.web: DEBUG  # Log Spring Web
    root: INFO  # Log all project

