server:
  port: 8080

spring:
  application:
    name: gateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            # Route 1: Identity Service
            - id: identity-service
              # lb:// = Load Balancer - Gateway sẽ tự động tìm service qua Eureka
              # identity-svc = Tên service đã đăng ký trong Eureka
              uri: lb://identity-svc
              # Predicate: Điều kiện để route này được áp dụng
              # Path=/api/identity/** = Tất cả request có path bắt đầu bằng /api/identity/
              predicates:
                - Path=/api/identity/**
              # Filters: Các bộ lọc áp dụng cho route này
              filters:
                - StripPrefix=0 # Giữ nguyên path gốc khi request

            # Route 2: Event Catalog Service
            - id: event-catalog-service
              uri: lb://event-catalog-svc
              predicates:
                - Path=/api/events/**
              filters:
                - StripPrefix=0
          globals:
            cors-configurations:
              '[/**]': # Áp dụng cho tất cả paths
                allowedOrigins: "*"  # Cho phép tất cả domain
                allowedMethods:
                  - GET
                  - POST
                  - PUT
                  - DELETE
                  - OPTIONS
                allowedHeaders: "*"  # Cho phép tất cả headers
                allowCredentials: true  # Cho phép gửi cookies/credentials
          default-filters:
            # bỏ header trùng lặp trong CORS response
            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin

# Redis
redis:
  host: localhost
  port: 6379
  timeout: 2000ms

# Eureka Client
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true   # Lấy danh sách service từ Eureka
    register-with-eureka: true  # Đăng ký Gateway với Eureka
  instance:
    prefer-ip-address: true  # Dùng IP thay vì hostname

# JWT
security:
   jwt:
    signerKey: ${JWT_SIGNER_KEY:secret-key-for-hmac-sha256}

    jwks-url: http://localhost:8081/api/identity/auth/jwks
    issuer: vticket-identity
    public_api:
      - POST:/api/identity/auth/login
      - POST:/api/identity/auth/register
      - POST:/api/identity/auth/refresh
      - GET:/api/identity/auth/jwks
      - POST:/api/identity/token/introspect
      - GET:/api/events/**
    protected_api:
      - POST:/api/events/category/**:ADMIN
      - POST:/api/events/**:ADMIN
      - DELETE:/api/events/**:ADMIN

# logging
logging:
  level:
    com.vticket.gateway: DEBUG  # Log package gateway
    org.springframework.cloud.gateway: DEBUG  # Log Spring Cloud Gateway
    org.springframework.web: DEBUG  # Log Spring Web
    root: INFO  # Log all project

