server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: gateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            # Route 1: Identity Service
            - id: identity-service
              # lb:// = Load Balancer - Gateway sẽ tự động tìm service qua Eureka
              # identity-svc = Tên service đã đăng ký trong Eureka
              uri: lb://identity-svc
              # Predicate: Điều kiện để route này được áp dụng
              # Path=/api/identity/** = Tất cả request có path bắt đầu bằng /api/identity/
              predicates:
                - Path=/api/identity/**
              # Filters: Các bộ lọc áp dụng cho route này
              filters:
                - StripPrefix=0 # Giữ nguyên path gốc khi request

            # Route 2: Event Catalog Service
            - id: event-catalog-service
              uri: lb://event-catalog-svc
              predicates:
                - Path=/api/events/**
              filters:
                - StripPrefix=0
          globals:
            cors-configurations:
              '[/**]': # Áp dụng cho tất cả paths
                allowedOrigins: "*"  # Cho phép tất cả domain
                allowedMethods:
                  - GET
                  - POST
                  - PUT
                  - DELETE
                  - OPTIONS
                allowedHeaders: "*"  # Cho phép tất cả headers
                allowCredentials: true  # Cho phép gửi cookies/credentials
          default-filters:
            # bỏ header trùng lặp trong CORS response
            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin

# Redis
redis:
  host: ${REDIS_HOST:localhost}
  port: ${REDIS_PORT:6379}
  timeout: ${REDIS_TIMEOUT:2000ms}

# Eureka Client
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true   # Lấy danh sách service từ Eureka
    register-with-eureka: true  # Đăng ký Gateway với Eureka
  instance:
    prefer-ip-address: true  # Dùng IP thay vì hostname

# JWT
security:
  jwt:
    jwks-url: ${JWT_JWKS_URL:http://localhost:8081/api/identity/auth/jwks}
    issuer: ${JWT_ISSUER:vticket-identity}

    public_api:
      - ${PUBLIC_API_1:GET:/api/events/**}
      - ${PUBLIC_API_2:POST:/api/identity/auth/login}
      - ${PUBLIC_API_3:POST:/api/identity/auth/register}
      - ${PUBLIC_API_4:GET:/api/identity/auth/jwks}
      - ${PUBLIC_API_5:POST:/api/identity/token/introspect}

    protected_api:
      - ${PROTECTED_API_1:POST:/api/events/**:ADMIN}
      - ${PROTECTED_API_2:DELETE:/api/events/**:ADMIN}

# Logging
logging:
  level:
    com.vticket.gateway: DEBUG  # Log package gateway
    org.springframework.cloud.gateway: DEBUG  # Log Spring Cloud Gateway
    org.springframework.web: DEBUG  # Log Spring Web
    root: INFO  # Log all project

