server:
  port: 8081

spring:
  application:
    name: identity-svc
  
  # MySQL
  datasource:
    url: jdbc:mysql://localhost:3306/vshow_identity
    username: root
    password: 1234554321
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
  
  # MongoDB
  data:
    mongodb:
      uri: mongodb://localhost:27017/vshow_identity

# Eureka Client
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true   # Lấy danh sách service từ Eureka
    register-with-eureka: true  # Đăng ký service này với Eureka
  instance:
    prefer-ip-address: true  # Dùng IP thay vì hostname

# JWT
security:
  jwt:
    signerKey: ${JWT_SIGNER_KEY}
    accessTokenExpirationMinutes: 60
    refreshTokenExpirationDays: 7

    issuer: vticket-identity
    access-token-ttl-seconds: 3600

    active-kid: k1

    keys:
      - kid: k1
        private-pem: classpath:properties.cert/k1-private.pem
        public-pem: classpath:properties.cert/k1-public.pem

# Logging
logging:
  level:
    com.vticket.identity: DEBUG  # Log package identity
    org.springframework.security: DEBUG  # Log Spring Security
    org.hibernate.SQL: DEBUG  # Log SQL
    root: INFO  # Log chung

